name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    name: cypress run
    runs-on: chrome 
    steps:
      - name: Checkout
        #nombre de la carpeta
        uses: demoweb  
        #nombre del proyecto en el dashboard
      - name: Cypress run
        uses: cypress-io/github-Product Store
        with:
          record: true
          start: npm start
         env:
          #pass the dasboard
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          #id proyect
          CYPRESS_ID_PROYECT: ${{ secrets.CYPRESS_ID_PROYECT }}
          #TOKEN GITHUB
          TOKENGITHUB: ${{ secrets.TOKENGITHUB }}
